add team to repo

diff --git a/.github/workflows/create_repository.yml b/.github/workflows/create_repository.yml
--- a/.github/workflows/create_repository.yml
+++ b/.github/workflows/create_repository.yml
@@ -39,7 +39,14 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Zero Pad
-        run: echo "PADDED_COUNTER=$(printf '%03d' ${{ env.COUNTER }})" >> $GITHUB_ENV
+        id: padding
+        run: echo "COUNTER=$(printf '%03d' ${{ env.COUNTER }})" >> $GITHUB_ENV
+
+      - name: Zero Padded
+        if: ${{ env.COUNTER == '' || env.COUNTER == '000'}}
+        run: |
+          echo "${{ env.COUNTER }}"
+          exit 1
 
       - name: GitHub Authorization
         uses: actions/create-github-app-token@v1
@@ -48,6 +55,10 @@ jobs:
           app-id: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_ID }}
           private-key: ${{ secrets.PFIKEST_REPOSITORY_MANAGER_SECRET }}
           owner: ${{ github.repository_owner }}
+
+      - name: Set Repository Name
+        run: |
+          echo "REPO_NAME=terraform-rg-${{ env.ROLE }}-${{ env.PADDED_COUNTER }}" >> $GIHUB_ENV
 
       - name: Create Repository
         if: ${{ env.PADDED_COUNTER != '' && env.PADDED_COUNTER != '000'}}
@@ -59,6 +70,13 @@ jobs:
             -H "Authorization: Bearer ${{ steps.app_token.outputs.token }}" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/${{ github.repository_owner }}/WorkloadTemplate/generate \
-            -d '{"owner":"PfikestInt","name":"terraform-rg-${{ env.ROLE }}-${{ env.PADDED_COUNTER }}","description":"${{ env.DESCRIPTION }}","include_all_branches":true,"private":false}' > results.json && \
+            -d '{"owner":"${{ github.repository_owner }}","name":"terraform-rg-${{ env.ROLE }}-${{ env.PADDED_COUNTER }}","description":"${{ env.DESCRIPTION }}","include_all_branches":true,"private":false}' > results.json && \
           export REPO_URL=$(jq '.html_url' results.json)
+          if [[ $REPO_URL == "" || $REPO_URL == null ]] then \
+            echo "Failed to create repo: ${{}}'";
+            exit 1;
+          fi
+
           echo "Created: ${REPO_URL}"
+
+      - name: Add Team
